#ifndef CA_CERT_H
#define CA_CERT_H
const char *ca_cert_pem =
"-----BEGIN CERTIFICATE-----\n"
"MIIDoTCCAomgAwIBAgIUJtwAbmaj2g4vViaMb5T85LXoAi4wDQYJKoZIhvcNAQEL\n"
"BQAwYDELMAkGA1UEBhMCQVIxDTALBgNVBAgMBENBQkExDTALBgNVBAcMBENBQkEx\n"
"DjAMBgNVBAoMBUZJVUJBMQswCQYDVQQLDAJDQTEWMBQGA1UEAwwNMTkyLjE2OC4w\n"
"LjE5MzAeFw0yNTA0MjMwODI4NDZaFw0yNjA0MjMwODI4NDZaMGAxCzAJBgNVBAYT\n"
"AkFSMQ0wCwYDVQQIDARDQUJBMQ0wCwYDVQQHDARDQUJBMQ4wDAYDVQQKDAVGSVVC\n"
"QTELMAkGA1UECwwCQ0ExFjAUBgNVBAMMDTE5Mi4xNjguMC4xOTMwggEiMA0GCSqG\n"
"SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDOsQaKa9EkM/R9nd7hkl4maOTfxWctgIfQ\n"
"1lQVFnXUSwOewf7HacK+fUAM/Sb+3cXWv4qVr8bysjLD6hzBOdfGgX2kiXxLC+2j\n"
"Hr7iJA1RwSlR4IQnc3WnDe12AURhE7NO+wyhkUN2rxrt86fGeP2M2UQDZ6zQUEi4\n"
"BgAY3WgpFawGQ49Yd4giSEoQVCRvOmfaKbOVDLjxtGO+XegiU1qDee15pKzHtzkz\n"
"gVrcntF5cLRHjPwjktZMgW5wJZVjKKyhYfpVQpZ0/EvEv4E5WuJjNufWskOi9HAT\n"
"RMlEJpFcdGqsrC7Yl2t/60AWxnArXxq02C3KYLVvMuVKHSxtCsTzAgMBAAGjUzBR\n"
"MB0GA1UdDgQWBBTuW4fmDYz+EtvkVZJ34r4TJ2A4yzAfBgNVHSMEGDAWgBTuW4fm\n"
"DYz+EtvkVZJ34r4TJ2A4yzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA\n"
"A4IBAQBcH+wxqiB3nRLY5Gb6CfKhQCR/cYqVqSj9HVnbctt1ew7LY4XydjfiDwXr\n"
"GLhBlw0vN5v3/KdOyusQmXx4WngfdETzUJm2HXhKqNZGEHKDpKBkgrYZywt4B6xT\n"
"XGghS1taXeZ1GaNvhBgXI7r46gbRyesb+QMxZL1XKmqFdL/rsjlY3GmsLIx9CeV/\n"
"zuI970rKhz0+TYOHO+gqqrfsyshDKuDfCF2Touc0DnOmRKp+C8IlHfmjxhrlvA7s\n"
"vdNHR/GYyyme8CMb4R+3vE4HDQxO9nRvbDRCKZWRYDVGvQ8yIKETPqJuGVz3tMYj\n"
"a4wG0CudZ2hkJEJh7fi5S196ERX5\n"
"-----END CERTIFICATE-----\n";

#endif
