#ifndef CLIENT_CERT_H
#define CLIENT_CERT_H
const char *client_cert_pem =
"-----BEGIN CERTIFICATE-----\n"
"MIIDlDCCAnygAwIBAgIUAWVnRPxysWaQ6qZfBB7KCyPUIbowDQYJKoZIhvcNAQEL\n"
"BQAwYDELMAkGA1UEBhMCQVIxDTALBgNVBAgMBENBQkExDTALBgNVBAcMBENBQkEx\n"
"DjAMBgNVBAoMBUZJVUJBMQswCQYDVQQLDAJDQTEWMBQGA1UEAwwNMTkyLjE2OC4w\n"
"LjE5MzAeFw0yNTA0MjMwODI4NDZaFw0yNjA0MjMwODI4NDZaMGQxCzAJBgNVBAYT\n"
"AkFSMQ0wCwYDVQQIDARDQUJBMQ0wCwYDVQQHDARDQUJBMQ4wDAYDVQQKDAVGSVVC\n"
"QTEPMA0GA1UECwwGQ2xpZW50MRYwFAYDVQQDDA0xOTIuMTY4LjAuMTkzMIIBIjAN\n"
"BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi9xFy72oIuY9Oqpw5s7Bgdi8OwrP\n"
"McBdjh11av1IuKuKbfDeJ/WbJyJBoKay+6397Uu6sABLEigQCYHHI1DQefxzmaQl\n"
"4LHxUHgnhpN0PhQcQFcITEJPWhD0CBg86FfIAmbJzOYRvb3I4Pl8pBid98/hcxlM\n"
"q+iAp67wgMTApMldWAgguNbZf7sskryBJCP1SvstWlpj7iO9mBvThYlO7DaP9wDQ\n"
"21q6qDTd0lbXdBUZaDollwZJtwkl8dHdBOo+biJwmahQ83yKVai+Z40kPVL3FGVC\n"
"8lA7uw5zkt5xGTGOVUe4r68P/4zLUczNd1lfe8GKcAcV+aqoswx507cyQwIDAQAB\n"
"o0IwQDAdBgNVHQ4EFgQU9OvmuQezREUsemPNquyu4F0mTLYwHwYDVR0jBBgwFoAU\n"
"7luH5g2M/hLb5FWSd+K+EydgOMswDQYJKoZIhvcNAQELBQADggEBAJ0Di0xFVhvi\n"
"42T+DWeK/G+sLwnET6slQmG64DqhRZWvwm9wEjckKwlIqLEn/3o7DfhnDnrD6aOC\n"
"rVDwnbrS5pcPZ6QfLrsW3DMlgmcMjM5xZsPIcdjqn8LQZiqKNF5Crooj+TQlTf62\n"
"at6TdMZmmdUu8N1uJeOiavPXOB2L3Wh6GipTYSaPMkkDB8dKC5srqpllr+qsLNRD\n"
"eVtXQG/1xCyQAXX6AcV04AcwlC3T3Yrxgp4L0VwDs3IJEiIzWUtVOeIqp4OeRqqY\n"
"sTN0zcNVv12okvJinsH7y6AFOZRPwTuDitBTUUMX/a8NfehgMge+fqLpLgaPmhCV\n"
"WG+VgcVr2Nc=\n"
"-----END CERTIFICATE-----\n";

#endif
