version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mqtt:
    build: ./mosquitto
    container_name: mqtt
#    image: eclipse-mosquitto
    ports:
      - "8883:8883"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - mqtt
    volumes:
      - ./backend:/usr/src/app
      - ./mosquitto/certs:/usr/src/app/certs
    working_dir: /usr/src/app
    command: npm start

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000/api
    #volumes:
    #  - ./frontend:/app
    #working_dir: /app
    #command: npm run dev
    #stdin_open: true
    #tty: true


volumes:
  mongo_data:
